from typing import Protocol, Sequence
from .types import MeshRef

class Logger(Protocol):
    def info(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
    def debug(self, msg: str) -> None: ...
    def warning(self, msg: str) -> None: ...

class MeshRepository(Protocol):
    def list_meshes_in(self, path: str) -> Sequence[MeshRef]: ...